name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 6.14.5
      - uses: actions/setup-node@v3
        with:
          node-version: '16.8.0'
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm run test -- --coverage || exit 1
